Add shellcheck to tests

diff --git a/bin/imposer b/bin/imposer
--- a/bin/imposer
+++ b/bin/imposer
@@ -22,20 +22,20 @@
 set -euo pipefail  # Strict mode
 mdsh-parse() {
 	local cmd=$1 lno=0 block_start lang block ln indent fence close_fence indent_remove
-	local open_fence='^( {0,3})(~~~+|```+) *([^`]*)$'
-	while let lno++; IFS= read -r ln; do
+	local open_fence=$'^( {0,3})(~~~+|```+) *([^`]*)$'
+	while ((lno++)); IFS= read -r ln; do
 		if [[ $ln =~ $open_fence ]]; then
 			indent=${BASH_REMATCH[1]} fence=${BASH_REMATCH[2]} lang=${BASH_REMATCH[3]} block=
 			block_start=$lno close_fence="^( {0,3})$fence+ *\$" indent_remove="^${indent// / ?}"
-			while let lno++; IFS= read -r ln && ! [[ $ln =~ $close_fence ]]; do
-				! [[ $ln =~ $indent_remove ]] || ln=${ln#$BASH_REMATCH}; block+=$ln$'\n'
+			while ((lno++)); IFS= read -r ln && ! [[ $ln =~ $close_fence ]]; do
+				! [[ $ln =~ $indent_remove ]] || ln=${ln#${BASH_REMATCH[0]}}; block+=$ln$'\n'
 			done
-			lang="${lang%"${lang##*[![:space:]]}"}"; $cmd fenced "$lang" "$block";
+			lang="${lang%"${lang##*[![:space:]]}"}"; "$cmd" fenced "$lang" "$block";
 		fi
 	done
 }
 mdsh-source() {
-	local MDSH_FOOTER= MDSH_SOURCE
+	local MDSH_FOOTER='' MDSH_SOURCE
 	if [[ ${1:--} != '-' ]]; then
 		MDSH_SOURCE="$1"
 		mdsh-parse __COMPILE__ <"$1"
@@ -47,32 +47,36 @@ mdsh-compile() (  # <-- force subshell to prevent escape of compile-time state
 	mdsh-source "$@"
 )
 __COMPILE__() {
-	[[ $1 == fenced && $fence == '```' && ! $indent ]] || return 0  # only unindented ``` code
+	[[ $1 == fenced && $fence == $'```' && ! $indent ]] || return 0  # only unindented ``` code
 	local lang="${2//[^_[:alnum:]]/_}"; # convert language to safe variable/function name
-	local tag_words=($2);  # check for command blocks first
+	local tag_words; mdsh-splitwords "$2" tag_words;  # check for command blocks first
 	if [[ ${tag_words[1]-} == '!'* ]]; then
 		set -- "$3" "$2" "$block_start"; eval "${2#*!}"; return
 	elif [[ ${tag_words[1]-} == '+'* ]]; then
-		printf "%s %q\n" "${2#"$tag_words"*+}" "$3"
+		printf '%s %q\n' "${2#"${tag_words[0]}"*+}" "$3"
 	elif [[ ${tag_words[1]-} == '|'* ]]; then
-		echo "${2#"$tag_words"*|} <<'\`\`\`'"; printf '%s```\n' "$3"; return
-	elif fn-exists mdsh-lang-$lang; then
-		mdsh-rewrite mdsh-lang-$lang "{" "} <<'\`\`\`'"; printf '%s```\n' "$3"
-	elif fn-exists mdsh-compile-$lang; then
-		mdsh-compile-$lang "$3" "$2" "$block_start"
+		echo "${2#"${tag_words[0]}"*|} <<'\`\`\`'"; printf $'%s```\n' "$3"; return
+	elif fn-exists "mdsh-lang-$lang"; then
+		mdsh-rewrite "mdsh-lang-$lang" "{" "} <<'\`\`\`'"; printf $'%s```\n' "$3"
+	elif fn-exists "mdsh-compile-$lang"; then
+		"mdsh-compile-$lang" "$3" "$2" "$block_start"
 	else
 		mdsh-misc "$2" "$3"
 	fi
 
-	if fn-exists mdsh-after-$lang; then
-		mdsh-rewrite mdsh-after-$lang
+	if fn-exists "mdsh-after-$lang"; then
+		mdsh-rewrite "mdsh-after-$lang"
 	fi
+}
+# split words in $1 into the array named by $2 (REPLY by default), without wildcard expansion
+mdsh-splitwords() {
+	set -f -- "$-" "$@";  eval "${3:-REPLY}"'=($2)'; [[ $1 == *f* ]] || set +f
 }
 # fn-exists: succeed if argument is a function
 fn-exists() { declare -F -- "$1"; } >/dev/null
 # Output body of func $1, optionally replacing the opening/closing { and } with $2 and $3
 mdsh-rewrite() {
-	declare -f $1 | sed -e '1d; 2s/^{ $/'"${2-"{"}"'/; $s/^}$/'"${3-"\}"}"'/'
+	local b='}' r; r="$(declare -f -- "$1")"; r=${r#*{ }; r=${r%\}*}; echo "${2-{}$r${3-$b}"
 }
 mdsh-misc()          { mdsh-data "$@"; }    # Treat unknown languages as data
 mdsh-compile-()      { :; }                 # Ignore language-less blocks
@@ -83,13 +87,13 @@ mdsh-compile-mdsh_main() { ! @is-main || eval "$1"; }
 mdsh-compile-shell() { printf '%s' "$1"; }  # Copy `shell` blocks to the output
 mdsh-compile-shell_main() { ! @is-main || printf '%s' "$1"; }
 mdsh-data() {
-	printf "mdsh_raw_${1//[^_[:alnum:]]/_}+=(%q)\n" "$2"
+	printf 'mdsh_raw_%s+=(%q)\n' "${1//[^_[:alnum:]]/_}" "$2"
 }
 mdsh-compile-shell_mdsh() {
-	indent= fence='```' __COMPILE__ fenced mdsh "$1"
+	indent='' fence=$'```' __COMPILE__ fenced mdsh "$1"
 }
 mdsh-compile-shell_mdsh_main() {
-	indent= fence='```' __COMPILE__ fenced "mdsh main" "$1"
+	indent='' fence=$'```' __COMPILE__ fenced "mdsh main" "$1"
 }
 # Main program: check for arguments and run markdown script
 mdsh-main() {
@@ -107,7 +111,7 @@ mdsh-main() {
 # MDSH_ZERO pointing to the original $0.
 
 function mdsh-interpret() {
-	printf -v cmd 'eval "$(%q --compile %q)"' "$0" "$1"
+	printf -v cmd $'eval "$(%q --compile %q)"' "$0" "$1"
 	MDSH_ZERO="$1" exec bash -c "$cmd" "" "${@:2}"
 }
 mdsh.--compile() {
@@ -119,7 +123,7 @@ mdsh.--compile() {
 
 mdsh.-c() { mdsh.--compile "$@"; }
 mdsh.--eval() {
-	(($# == 1)) && [[ $1 != - ]] ||
+	{ (($# == 1)) && [[ $1 != - ]]; } ||
 		mdsh-error "Usage: %s --eval FILENAME" "${0##*/}"
 	mdsh.--compile "$1"
 	echo $'__status=$? eval \'return $__status || exit $__status\' 2>/dev/null'
@@ -135,10 +139,11 @@ mdsh.--out() {
 
 mdsh.-o() { mdsh.--out "$@"; }
 # mdsh-error: printf args to stderr and exit w/EX_USAGE (code 64)
-mdsh-error() { printf "$1\n" "${@:2}" >&2; exit 64; }
+# shellcheck disable=SC2059  # argument is a printf format string
+mdsh-error() { printf "$1"'\n' "${@:2}" >&2; exit 64; }
 mdsh.--help() {
-	printf "Usage: %s [--out FILE] [ --compile | --eval ] markdownfile [args...]\n" "${0##*/}"
-	echo -e '
+	printf 'Usage: %s [--out FILE] [ --compile | --eval ] markdownfile [args...]\n' "${0##*/}"
+	echo $'
 Run and/or compile code blocks from markdownfile(s) to bash.
 Use a filename of `-` to run or compile from stdin.
 
@@ -185,7 +190,7 @@ mdsh-embed() {
 	}
 	contents=$'\n'$(<"$f")$'\n'
 	while [[ $contents == *$'\n'"$boundary"$'\n'* ]]; do
-		let ctr++; boundary="# --- EOF $base.$ctr ---"
+		((ctr++)); boundary="# --- EOF $base.$ctr ---"
 	done
 	printf $'{ if [[ $OSTYPE != cygwin && $OSTYPE != msys && -e /dev/fd/0 ]]; then source /dev/fd/0; else source <(cat); fi; } <<\'%s\'%s%s\n' "$boundary" "$contents" "$boundary"
 }
@@ -205,7 +210,7 @@ flatname() {
 }
 MDSH_CACHE=
 mdsh-use-cache() {
-	if !(($#)); then
+	if ! (($#)); then
 		set -- "${XDG_CACHE_HOME:-${HOME:+$HOME/.cache}}"
 		set -- "${1:+$1/mdsh}"
 	fi
@@ -223,6 +228,7 @@ mdsh-run() {
 # Compile `file` and source the result, passing along any positional arguments
 run-markdown() {
 	if [[ $BASH_VERSINFO == 3 ]]; then # bash 3 can't source from proc
+		# shellcheck disable=SC1091  # shellcheck shouldn't try to read stdin
 		source /dev/fd/0 "${@:2}" <<<"$(mdsh-source "${1--}")"
 	else source <(mdsh-source "${1--}") "${@:2}"
 	fi
@@ -242,12 +248,14 @@ mdsh-compile-jq_imports() { printf 'IMPORTS %q\n' "$1"$'\n'; }
 
 mdsh-compile-yml()  { y2j "$1"; mdsh-compile-json "$REPLY"; }
 mdsh-compile-yaml() { y2j "$1"; mdsh-compile-json "$REPLY"; }
+
+# shellcheck disable=SC2154  # jqmd_data is initialized by the runtime
 mdsh-compile-json() { mdsh-compile-jq "$jqmd_data($1)"; }
 
 const() {
 	case "${tag_words-}" in
-	yaml|yml) y2j "$block"; printf "DEFINE %q\n" "def $1: $REPLY ;"$'\n' ;;
-	json)     printf "DEFINE %q\n" "def $1: $block ;"$'\n' ;;
+	yaml|yml) y2j "$block"; printf 'DEFINE %q\n' "def $1: $REPLY ;"$'\n' ;;
+	json)     printf 'DEFINE %q\n' "def $1: $block ;"$'\n' ;;
 	*) mdsh-error "Invalid language for constant: '%s'" "${tag_words-}"
 	esac
 }
@@ -258,7 +266,7 @@ printf -v REPLY '%s\n' "${mdsh_raw_bash_runtime[@]}"; eval "$REPLY"
 printf -v REPLY 'mdsh:file-header() { ! @is-main || echo -n %q; }' "$REPLY"; eval "$REPLY"
 
 # Ensure (main) scripts process any leftover filters at end
-mdsh:file-footer() { ! @is-main || echo 'if [[ $0 == ${BASH_SOURCE-} ]] && HAVE_FILTERS; then RUN_JQ; fi'; }
+mdsh:file-footer() { ! @is-main || echo $'if [[ $0 == "${BASH_SOURCE[0]-}" ]] && HAVE_FILTERS; then RUN_JQ; fi'; }
 mdsh.--no-runtime() ( unset -f mdsh:file-header mdsh:file-footer; mdsh-main "$@"; )
 mdsh.--yaml() (
 	fn-exists "yaml2json:${1-}" || mdsh-error "No such yaml2json processor: ${1-}" || exit $?
@@ -270,34 +278,34 @@ mdsh.-R() { mdsh.--no-runtime "$@"; }
 mdsh.-y() { mdsh.--yaml "$@"; }
 #!/usr/bin/env bash
 
-realpath.location() { realpath.follow "$1"; realpath.absolute "$REPLY" ".."; }
-realpath.resolved() { realpath.follow "$1"; realpath.absolute "$REPLY"; }
-realpath.dirname()  { if [[ $1 =~ /+[^/]+/*$ ]]; then REPLY="${1%${BASH_REMATCH}}"; REPLY=${REPLY:-/}; else REPLY=.; fi }
-realpath.basename() { if [[ $1 =~ /*([^/]+)/*$ ]]; then REPLY="${BASH_REMATCH[1]}"; else REPLY=/; fi }
+realpath.location(){ realpath.follow "$1"; realpath.absolute "$REPLY" ".."; }
+realpath.resolved(){ realpath.follow "$1"; realpath.absolute "$REPLY"; }
+realpath.dirname() { if [[ $1 =~ /+[^/]+/*$ ]]; then REPLY="${1%${BASH_REMATCH[0]}}"; REPLY=${REPLY:-/}; else REPLY=.; fi }
+realpath.basename(){ if [[ $1 =~ /*([^/]+)/*$ ]]; then REPLY="${BASH_REMATCH[1]}"; else REPLY=/; fi }
 
 realpath.follow() {
 	local target
 	while [[ -L "$1" ]] && target=$(readlink -- "$1"); do
 		realpath.dirname "$1"
-		# Resolve symlink target relative to symlink's directory
+		# Resolve relative to symlink's directory
 		[[ $REPLY != . && $target != /* ]] && REPLY=$REPLY/$target || REPLY=$target
 		# Break out if we found a symlink loop
 		for target; do [[ $REPLY == "$target" ]] && break 2; done
-		# Add current result to the loop-detect list and tail-recurse
+		# Add to the loop-detect list and tail-recurse
 		set -- "$REPLY" "$@"
 	done
 	REPLY="$1"
 }
 
 realpath.absolute() {
-	REPLY=$PWD; local no_eg; shopt -q extglob || { no_eg=y; shopt -s extglob; }
+	REPLY=$PWD; local eg=extglob; ! shopt -q $eg || eg=; ${eg:+shopt -s $eg}
 	while (($#)); do case $1 in
 		/*) REPLY=/; set -- "${1##+(/)}" "${@:2}" ;;
 		*/*) set -- "${1%%/*}" "${1##${1%%/*}+(/)}" "${@:2}" ;;
 		''|.) shift ;;
 		..) realpath.dirname "$REPLY"; shift ;;
 		*) REPLY="${REPLY%/}/$1"; shift ;;
-	esac; done; ${no_eg:+shopt -u extglob}
+	esac; done; ${eg:+shopt -u $eg}
 }
 
 realpath.canonical() {
@@ -322,7 +330,7 @@ realpath.relative() {
 set -euo pipefail
 
 fn_exists() { declare -F -- "$1"; } >/dev/null
-fn_copy()   { REPLY="$(declare -f $1)"; eval "$2 ${REPLY#$1}"; }
+fn_copy()   { REPLY="$(declare -f "$1")"; eval "$2 ${REPLY#$1}"; }
 findup()    { walkup "${1:-$PWD}" reply_if_exists "${@:2}"; }
 
 reply_if_exists() {
@@ -361,6 +369,7 @@ _loco_do() {
 }
 
 _loco_findproject() {
+    # shellcheck disable=SC2015  # plain var assign can't be false
     findup "$LOCO_PWD" "${LOCO_FILE[@]}" && LOCO_PROJECT=$REPLY ||
         loco_error "Can't find $LOCO_FILE here";
 }
@@ -374,6 +383,7 @@ _loco_user_config() { source "$1"; }
 
 # Find our configuration, exposing relevant paths and defaults
 
+# shellcheck disable=SC2034  # some vars are only used by extending scripts
 _loco_config() {
     LOCO_ARGS=("$@")
     loco_preconfig "$@"
@@ -394,7 +404,7 @@ _loco_config() {
 
 _loco_main() {
     loco_config "$@"
-    fn_exists $LOCO_NAME || eval "$LOCO_NAME() { loco_do \"\$@\"; }"
+    fn_exists "$LOCO_NAME" || eval "$LOCO_NAME() { loco_do \"\$@\"; }"
     ${LOCO_PROJECT:+:} loco_findproject "$@"
     ${LOCO_ROOT:+:}    loco_findroot "$@"
     loco_loadproject "$LOCO_PROJECT"
@@ -407,34 +417,34 @@ for f in $(compgen -A function _loco_); do
 done
 
 # Clear all LOCO_*  variables before beginning
-for lv in ${!LOCO_@}; do unset $lv; done
+for lv in ${!LOCO_@}; do unset "$lv"; done
 
 LOCO_SCRIPT=$0
 event(){ case $1 in error|quote|encode);; *)
-	__ev.encode "${2-}";local f n= e=bashup_event_$REPLY;f=${e/event/flag}
+	__ev.encode "${2-}";local f n='' e=bashup_event_$REPLY;f=${e/event/flag}
 	case $1 in emit) shift;${!f-};eval "${!e-}"; return ;;on|once|off|has)
 		case "${3-}" in @_) n='$#';; @*[^0-9]*);; @[0-9]*) n=$((${3#@}));; esac; ${n:+
 		set -- "$1" "$2" "${@:4}" }
 		case $1/$# in
-			has/[12]) REPLY=;; */[12]) set error "${2-}: missing callback";;
-			*) __ev.quote "${@:3}";! ((${n/\$#/1}))||REPLY+=' "${@:2:'"$n"'}"';REPLY+=$'\n'
+			has/[12]) REPLY=;; */[12]) set -- error "${2-}: missing callback";;
+			*) __ev.quote "${@:3}";((${n/\$#/1}))&&REPLY+=' "${@:2:'"$n"'}"';REPLY+=$'\n'
 		esac
 	esac
 esac ;__ev."$@";}
-__ev.error(){ echo "$1">&2;return ${2:-64};}
-__ev.quote(){ REPLY=; printf -v REPLY "${@+ %q}" "${@-}"; REPLY=${REPLY# };}
+__ev.error(){ echo "$1">&2;return "${2:-64}";}
+__ev.quote(){ REPLY=; ${@+printf -v REPLY ' %q' "$@"}; REPLY=${REPLY# };}
 __ev.has(){ [[ ${!e-} && $'\n'"${!e}" == *$'\n'"$REPLY"* && ! ${!f-} ]];}
-__ev.on(){ __ev.has && return;[[ ! ${!f-} ]]&&eval $e+='$REPLY'||eval "${!e-};$REPLY";}
-__ev.off(){ __ev.has||return 0; n="${!e}"; n=${n#"$REPLY"}; eval $e=$'"${n//\n"$REPLY"/\n}"';}
+__ev.on(){ __ev.has && return;if [[ ! ${!f-} ]];then eval "$e"+='$REPLY';else eval "${!e-};$REPLY";fi;}
+__ev.off(){ __ev.has||return 0; n="${!e}"; n=${n#"$REPLY"}; eval "$e"=$'"${n//\n"$REPLY"/\n}"';}
 __ev.fire(){ ${!f-};set -- "$e" "${@:2}"; while [[ ${!1-} ]];do eval "$1=;${!1}"; done ;}
 __ev.all(){ ${!f-};e=${!e-};eval "${e//$'\n'/||return; }";}
 __ev.any(){ ${!f-};e=${!e-};eval "${e//$'\n'/&&return|| } ! :";}
 __ev.resolve(){
 	${!f-};__ev.fire "$@";__ev.quote "$@"
-	readonly $f="eval __ev.error 'event \"'$1'\" already resolved' 70;return" $e="set -- $REPLY"
+	readonly "$f=eval __ev.error 'event \"'$1'\" already resolved' 70;return" "$e=set -- $REPLY"
 }
 __ev.resolved(){ [[ ${!f-} ]];}
-__ev.once(){ n=${n:-0} n=${n/\$#/_}; event on "$1" @$n __ev_once $# @$n "$@";}
+__ev.once(){ n=${n:-0} n=${n/\$#/_}; event on "$1" "@$n" __ev_once $# "@$n" "$@";}
 __ev_once(){ event off "$3" "$2" __ev_once "${@:1:$1+2}"; "${@:4}";}
 __ev_jit(){
 	local r=${__ev_jit-} s=$1;((${#r}<250))||__ev_jit=
@@ -500,7 +510,7 @@ imposer_dirs=()
 wpcon() { wp "$@" --skip-plugins --skip-themes --skip-packages; }
 
 get_imposer_dirs() {
-    if [[ ${imposer_dirs[@]+_} ]]; then
+    if [[ ${imposer_dirs+_} ]]; then
         return
     elif (($#)); then
         true
@@ -524,7 +534,7 @@ get_imposer_dirs() {
 } 2>/dev/null
 imposer.path() {
     get_imposer_dirs;
-    if [[ ${imposer_dirs[@]+_} ]]; then IFS=: eval 'echo "${imposer_dirs[*]}"'; fi
+    if [[ ${imposer_dirs+_} ]]; then IFS=: eval 'echo "${imposer_dirs[*]}"'; fi
 }
 
 imposer.default-path() { local imposer_dirs=() IMPOSER_PATH=; imposer path; }
@@ -532,7 +542,7 @@ compile-php() {
     if REPLY="$(echo "<?php $2" | php -l 2>&1)"; local s=$?; ((s)); then
         php-error "$REPLY" $s "${3-}"; return
     elif php-uses-namespace "$2"; then
-        if [[ $REPLY != { ]]; then
+        if [[ $REPLY != '{' ]]; then
             php-error "Namespaces in PHP blocks must be {}-enclosed" 255 "${3-}"; return
         fi
         printf 'compact-php %s %s[1] force\n' "$1" "$1"
@@ -544,7 +554,7 @@ compile-php() {
 }
 
 php-error() {
-    echo "In PHP block ${3:+at line ${3-} }of ${MDSH_SOURCE--}:"$'\n'"$1" >&2; return $2
+    echo "In PHP block ${3:+at line ${3-} }of ${MDSH_SOURCE--}:"$'\n'"$1" >&2; return "$2"
 }
 
 maybe-compact-php() {
@@ -556,7 +566,7 @@ maybe-compact-php() {
 
 compact-php() {
     if [[ "${!1-}${3-}" && "${!2-}" ]]; then
-        printf -v $1 '%snamespace {\n%s}\n' "${!1-}" "${!2}"; unset $2
+        printf -v "$1" '%snamespace {\n%s}\n' "${!1-}" "${!2}"; unset "$2"
     fi
 }
 
@@ -572,16 +582,16 @@ mdsh-compile-php() { compile-php imposer_php "$1" "$3"; }
 cat-php() {
     local v1 v2 t php=()
     while (($#)); do
-        v1=$1 v2=$1[1]; compact-php $v1 $v2; t=${!v1-}${!v2-}
+        v1=$1 v2="$1[1]"; compact-php "$v1" "$v2"; t=${!v1-}${!v2-}
         if php-uses-namespace "$t"; then
             compact-php php php[1] force
-            php+="$t"
+            php[0]+="$t"
         else
             php[1]+="$t"
         fi
         shift
     done
-    printf "<?php\n%s" "${php-}${php[1]-}"
+    printf '<?php\n%s' "${php-}${php[1]-}"
 }
 if [[ $0 == "${BASH_SOURCE-}" ]]; then
     realpath.dirname "$0"
@@ -610,14 +620,15 @@ have_module() {
     local patterns=("$1" "$1/default" "$1/imposer-states/default" "$ns/imposer-states/$name" )
     for REPLY in ${imposer_dirs[@]+"${imposer_dirs[@]}"}; do
         if reply_if_exists "$REPLY" "${patterns[@]/%/.state.md}"; then
-            printf -v $v %s "$REPLY"; return
+            printf -v "$v" %s "$REPLY"; return
         fi
     done
-    printf -v $v %s ""
+    printf -v "$v" %s ""
     false
 }
 __load_module() {
     realpath.dirname "$2"
+    # shellcheck disable=SC2034  # vars for users + event var
     local __FILE__="$2" __DIR__=$REPLY IMPOSER_MODULE="$1" bashup_event_after__module=
     mark-read "$2"
     MDSH_CACHE=${IMPOSER_CACHE-$LOCO_ROOT/imposer/.cache} mdsh-run "$2" "$1"
@@ -694,7 +705,8 @@ write-plugin() {
 }
 
 capture-tweaks() {
-    captured_tweaks=("${php_tweaks-}" "${php_tweaks[1]-}"); unset php_tweaks[@]
+    # shellcheck disable=SC2034  # captured_tweaks is used in previous function above
+    captured_tweaks=("${php_tweaks-}" "${php_tweaks[1]-}"); unset "php_tweaks[@]"
     event off "php_tweak" activate-tweaks
     event on  "php_tweak" event on "after_module" warn-unloaded-tweaks
 }
@@ -705,7 +717,7 @@ event on "php_tweak" activate-tweaks
 mdsh-compile-php_tweak() { echo 'event emit php_tweak'; compile-php php_tweaks "$1" "$3"; }
 
 imposer.tweaks()  {
-    if (($#)); then echo '`imposer tweaks` does not accept arguments' >&2; exit 64; fi
+    if (($#)); then echo $'`imposer tweaks` does not accept arguments' >&2; exit 64; fi
     run-modules; CLEAR_FILTERS
     tty pager colorize-php -- cat-php captured_tweaks
 }
@@ -759,7 +771,7 @@ imposer.options---dir() {
 loco_subcommand() { if fn-exists "${1}${3-}"; then "${1}${@:3}"; else "${@:2}"; fi; }
 
 loco_subcommand_help() {
-	REPLY=($(compgen -A function "$1"))
+	REPLY=$(compgen -A function "$1") && mdsh-splitwords "$REPLY"
 	printf -v REPLY '\n    %s' "${REPLY[@]#$1}"
 	printf -v REPLY 'Usage: %s COMMMAND [ARGS...]\n\n%s'${3:+'\n\n'}'Commands:\n%s' \
 		"$2" "${3-}" "$REPLY"
@@ -797,16 +809,16 @@ imposer.options-watch() {
 }
 
 watch-continuous() {
-	local interval=$1 status oldint=$(trap -p SIGINT) oldwinch="$(trap -p SIGWINCH)"
+	local interval=$1 oldint oldwinch; oldint=$(trap -p SIGINT); oldwinch="$(trap -p SIGWINCH)"
 	shift; trap "continue" SIGWINCH; trap "break" SIGINT
-	while :; do watch-once "$@"; sleep $interval & wait $! || true;	done
+	while :; do watch-once "$@"; sleep "$interval" & wait $! || true;	done
 	${oldwinch:-trap -- SIGWINCH}; ${oldint:-trap -- SIGINT}
 }
 
 watch-once() {
 	local cols; cols=$(tput cols) 2>/dev/null || cols=80
 	REPLY="Every ${interval}s: $*"
-	clear; printf "%s%*s\n\n" "$REPLY" $((cols-${#REPLY})) "$(date "+%Y-%m-%d %H:%M:%S")"
+	clear; printf '%s%*s\n\n' "$REPLY" $((cols-${#REPLY})) "$(date "+%Y-%m-%d %H:%M:%S")"
 	IMPOSER_PAGER="pager.screenfull 3" "$@" || true
 }
 if [[ $0 == "${BASH_SOURCE-}" ]]; then loco_main "$@"; fi
